services:
  caddy:
    build:
      context: .
      dockerfile: ./caddy/Dockerfile
    container_name: transcendence-caddy
    ports:
      - "8080:80"
      - "8443:443"
    depends_on: [backend, database]
    networks: [transnet]

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: transcendence-backend
    environment:
      - JWT_SECRET=${JWT_SECRET}
    networks: [transnet]

  database:
    build: ./database
    container_name: transcendence-db
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=https://localhost:8443
      - GOOGLE_REDIRECT_URI=https://localhost:8443/api/auth/google/callback
      - DB_PATH=/app/data/users.db
    volumes:
      - ./database/data:/app/data
    networks: [transnet]


networks:
  transnet:
    driver: bridge
