services:
  caddy:
    build:
      context: .
      dockerfile: ./caddy/Dockerfile
    container_name: transcendence-caddy
    ports:
      - "8080:80"
      - "8443:443"
    depends_on: [backend, database]
    networks: [transnet]
    volumes:
      - ./database/data/uploads:/usr/share/caddy/uploads

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: transcendence-backend
    environment:
      - JWT_SECRET=${JWT_SECRET}
    networks: [transnet]

  database:
    build: ./database
    container_name: transcendence-db
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - DB_PATH=${DB_PATH}
      - UPLOADS_DIR=${UPLOADS_DIR}

    volumes:
      - ./database/data:/app/data
      - ./database/data/uploads:/app/uploads
    networks: [transnet]


networks:
  transnet:
    driver: bridge
