services:
  caddy:
    build:
      context: .
      dockerfile: ./caddy/Dockerfile
    container_name: transcendence-caddy
    ports:
      - "8080:80"
      - "8443:443"
    depends_on: [backend]
    networks: [transnet]

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: transcendence-backend
    networks: [transnet]


networks:
  transnet:
    driver: bridge