services:
  caddy:
    build:
      context: .
      dockerfile: ./caddy/Dockerfile
    container_name: transcendence-caddy
    ports:
      - "8080:80"
      - "8443:443"
    depends_on: [backend]
    networks: [transnet]

  backend:
    build: ./backend
    container_name: transcendence-backend
    depends_on:
      - engine
    networks: [transnet]

  engine:
    build: ./engine
    container_name: transcendence-engine
    networks: [transnet]

networks:
  transnet:
    driver: bridge